image: cirrusci/flutter:2.10.3

before_script:
    - cat $PUB_DEV_CREDENTIALS > ~/.pub-cache/credentials.json
    - export PATH="$PATH":"$HOME/.pub-cache/bin"

Validate MR:
    stage: test
    script:
        - flutter pub publish --dry-run
    only:
        - merge_requests

Publish Release:
    stage: deploy
    script:
        - flutter pub get
        - flutter pub publish -f
    only:
        - tags
